services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/www/mysql

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

volumes:
  mariadb_data: